INSERT INTO employees (name, role, profile_code, unit, status, cpf) VALUES 
('Carla Liziane Carrion Rockembach', 'Coordenador(a) Compras', 'C-0079', 'Sede', 'Ativo', NULL),
('Claudia da Fonseca Leitzke', 'Supervisor(a) Administrativo(a)', 'C-0160', 'Sede', 'Ativo', NULL),
('Jennifer Cazaubon da Silva', 'Diretor(a) Administrativo(a) e Financeiro(a)', 'C-0157', 'Sede', 'Ativo', NULL),
('Leonardo Bederode dos Santos', 'Coordenador(a) de SMS', 'C-0023', 'Sede', 'Ativo', NULL),
('Luis Carlos Falcão Tuchtenhagen', 'Analista Técnico - (pós-obra)', 'C-0136', 'Sede', 'Ativo', NULL),
('Patricia Juarez Rodrigues', 'Coordenador (a) de Qualidade', 'C-0021', 'Sede', 'Ativo', NULL),
('Patricia Peres Gonçalves', 'Supervisor(a) Técnico(a)', 'C-0162', 'Sede', 'Ativo', NULL),
('Tacio Fernandes Ornos', 'Diretor Estratégico', NULL, 'Sede', 'Ativo', NULL),
('Carlos Eduardo Silva da Silva', 'Coordenador de Obras', 'C-0024', 'Obra', 'Ativo', NULL),
('Cleudete Maria Costa Gomes', 'Analista Contábil (Fiscal) -', 'C-0120', 'Sede', 'Ativo', NULL),
('Daiane Pinto Duarte', 'Analista de RH', 'C-0083', 'Sede', 'Ativo', NULL),
('Diogo Antônio dos Santos Soares', 'Analista de RH', 'C-0083', 'Sede', 'Ativo', NULL),
('Egicleide Dias Silva', 'Técnico(a) em Segurança do Trabalho', 'C-0052', 'Obra', 'Ativo', NULL),
('Flavio Tadeu de Lima Freitas Junior', 'Coordenador de Obras', 'C-0024', 'Obra', 'Ativo', NULL),
('Gabriel Eduardo Melo Hepp', 'Analista Técnico(a) - Obras', 'C-0136', 'Obra', 'Ativo', NULL),
('Gabriela Torres Silveira', 'Técnico(a) em edificações - Sede', 'C-0050', 'Sede', 'Ativo', NULL),
('Guilherme Louzada de Freitas', 'Assistente de Compras', 'C-0110', 'Sede', 'Ativo', NULL),
('Joice Alexandra Dos Santos Gonçalves', 'Analista Técnico(a) - Obras', 'C-0136', 'Obra', 'Ativo', NULL),
('Jorge Airton Ramaje Junior', 'Coordenador de Obras', 'C-0024', 'Obra', 'Ativo', NULL),
('Luiz Fernando Agostinho', 'Período de Experiência', NULL, 'Sede', 'Ativo', NULL),
('Matheus Vargas Zborowski', 'Analista de TI', 'C-0075', 'Sede', 'Ativo', NULL),
('Piero Costa Fernandes', 'Almoxarife', 'C-0001', 'Obra', 'Ativo', NULL),
('Priscila Hirschmann da Cruz', 'Analista Comercial', 'C-0147', 'Sede', 'Ativo', NULL),
('Vitoria Teixeira Pinto', 'Coordenador (a) de Planejamento', 'C-0172', 'Sede', 'Ativo', NULL),
('Cyntia Vasques Bender', 'Coordenador(a) de Projetos', 'C-0056', 'Sede', 'Ativo', NULL),
('Rafael de Almeida Coelho', 'Diretor Operacional', 'C-0151', 'Sede', 'Ativo', NULL),
('Ana Helena Dias Méndez', 'Coordenador(a) de Novos Negócios', 'C-0158', 'Sede', 'Ativo', NULL),
('Daniel Costa da Silveira', 'Projetista - Complementar', 'C-0047', 'Sede', 'Ativo', NULL),
('Felipe Almeida Coelho', 'Mestre de Obras', 'C-0042', 'Obra', 'Ativo', NULL),
('Gilmar Vergara Lopes', 'Analista Administrativo', 'C-0139', 'Obra', 'Ativo', NULL),
('Ruy Alberto Quincozes Porto', 'Coordenador de Obras', 'C-0024', 'Obra', 'Ativo', NULL),
('Victoria Iglesia Gomes Maurente', 'Projetista - Complementar', 'C-0047', 'Sede', 'Ativo', NULL),
('Osvaldo Luis Gimenes Amaro', 'Presidente', NULL, 'Sede', 'Ativo', NULL),
('Fernanda Clenir Hernandes da Silva', 'Analista Contábil (Fiscal) -', 'C-0120', 'Sede', 'Ativo', NULL),
('Jeniffer Pertili Bouchahine', 'Coordenador(a) Comercial', 'C-0090', 'Sede', 'Ativo', NULL),
('Eugênia Lucas Souza', 'Analista Administrativo - SAC', 'C-0139', 'Sede', 'Ativo', NULL),
('Murilo Vasconcelos Machado', 'Psicólogo(a) Organizacional', 'C-0118', 'Sede', 'Ativo', NULL),
('Tanara de Oliveira Wonglon Alves', 'Coordenador de Obras', 'C-0024', 'Obra', 'Ativo', NULL),
('Rodrigo Dias Lemos', 'Coordenador de Manutenção', 'C-0146', 'Sede', 'Ativo', NULL),
('Wesley Martins de Souza', 'Analista Técnico(a) - Obras', 'C-0136', 'Obra', 'Ativo', NULL),
('Andrei Carvalho Aquino', 'Analista Financeiro - Contas a Pagar', 'C-0073', 'Sede', 'Ativo', NULL),
('Everson Ferraz de Almeida', 'Mestre de Obras', 'C-0042', 'Sede', 'Ativo', NULL),
('Alessandro Soares Cardoso', 'Mestre de Obras', 'C-0042', 'Obra', 'Ativo', NULL),
('Cristina Cidade Rodrigues', 'Coordenador(a) Financeiro(a) -', 'C-0066', 'Sede', 'Ativo', NULL),
('Thais Shaillene Costa', 'Analista Técnico(a) - Obras', 'C-0136', 'Obra', 'Ativo', NULL),
('Valdilene Negrao de Farias', 'Técnico(a) em Segurança do Trabalho', 'C-0052', 'Obra', 'Ativo', NULL),
('Luis Mariano Cedrez Macedo', 'Mestre de Obras', 'C-0042', 'Obra', 'Ativo', NULL),
('Otávio Saraiva Loth', 'Auxiliar Técnico', 'C-0013', 'Obra', 'Ativo', NULL),
('Nathali dos Santos Porto', 'Auxiliar Administrativo - Financeiro', 'C-0009', 'Sede', 'Ativo', NULL),
('Ana Laura Farias Nunes Pereira', 'Analista Técnico(a) - Obras', 'C-0136', 'Obra', 'Ativo', NULL),
('Matheus Fonseca Rodrigues', 'Diretor Comercial', 'C-0156', 'Sede', 'Ativo', NULL),
('Talita Nunes Soares', 'Assistente de Orçamentos -', 'C-0107', 'Sede', 'Ativo', NULL),
('Thauany Vergara Brum', 'Assistente Técnico', 'C-0055', 'Obra', 'Ativo', NULL),
('Claison de Paula da Fonseca', 'Mecânico Líder', 'C-0071', 'Sede', 'Ativo', NULL),
('Moacir da Silva Bilhalva', 'Chapista de Veículos', 'C-0127', 'Sede', 'Ativo', NULL),
('Alexandre da Silva', 'Mecânico', 'C-0130', 'Sede', 'Ativo', NULL),
('Simone Marques Gomes', 'Auxiliar de Serviços Gerais', 'C-0057', 'Sede', 'Ativo', NULL),
('Diego dos Anjos Rockembach', 'Vigia', 'C-0053', 'Sede', 'Ativo', NULL),
('Dagoberto Antunes Leal', 'Presidente (Conselho)', NULL, 'Sede', 'Ativo', NULL),
('Gabriela Rodrigues Rubim', 'Coordenador(a) Comercial', 'C-0090', 'Sede', 'Ativo', NULL),
('Luana Braiz Gonçalves', 'Projetista - Legalizações', 'C-0047', 'Sede', 'Ativo', NULL),
('Rafaela Dias Gonçalves', 'Assistente Técnico (pós-obra)', 'C-0055', 'Sede', 'Ativo', NULL),
('Maicon Borges Cardoso', 'Mestre de Obras', 'C-0042', 'Obra', 'Ativo', NULL),
('Leonardo Karini Leitzke', 'Auxiliar Administrativo - Financeiro', 'C-0009', 'Sede', 'Ativo', NULL),
('Pedro Ezequiel Bauer Nunes De Almeida', 'Analista de Marketing (C-150)', NULL, 'Sede', 'Ativo', NULL),
('Fábio Pereira Leal', 'Coordenador de Obras', 'C-0024', 'Obra', 'Ativo', NULL),
('Alessandra Dias Alves', 'Assistente de Orçamentos -', 'C-0107', 'Sede', 'Ativo', NULL),
('Maurício Silva Vieira', 'Projetista', 'C-0047', 'Sede', 'Ativo', NULL),
('Gregori Das Neves Reinhardt', 'Assistente Técnico de Qualidade', 'C-0006', 'Obra', 'Ativo', NULL),
('Vaneza Brum Horner', 'Auxiliar de Serviços Gerais', 'C-0057', 'Sede', 'Ativo', NULL),
('Hans Krumreich Maltzhan', 'Assistente Técnico', 'C-0055', 'Sede', 'Ativo', NULL),
('Giovana Oliveira de Andrade', 'Analista de Marketing (C-150)', NULL, 'Sede', 'Ativo', NULL),
('Eduardo Soria Marques Viabilizador de', 'Vendas', 'C-0164', 'Sede', 'Ativo', NULL),
('Adriane Silveira dos Santos', 'Coordenador(a) Comercial', 'C-0090', 'Sede', 'Ativo', NULL),
('Natália Lohmann D'' Ávila', 'Projetista', 'C-0047', 'Sede', 'Ativo', NULL),
('Jorge Langlois Bouchahine', 'Coordenador(a) Comercial', 'C-0090', 'Sede', 'Ativo', NULL),
('Giovana Martins da Silva', 'Jovem Aprendiz', 'C-0076', 'Sede', 'Ativo', NULL),
('Henrique Oliveira Janner', 'Auxiliar Técnico', 'C-0013', 'Obra', 'Ativo', NULL),
('Bruna Fick Pacheco', 'Projetista - Complementar', 'C-0047', 'Sede', 'Ativo', NULL),
('Eliziane Rochel Gonçalves', 'Assistente de Marketing', 'C-0128', 'Sede', 'Ativo', NULL),
('Magno Peres de Oliveira', 'Mestre de Obras', 'C-0042', 'Obra', 'Ativo', NULL),
('Daniel de Paula Martins', 'Auxiliar de Almoxarifado', 'C-0010', 'Obra', 'Ativo', NULL),
('Guilherme Borges Lages', 'Auxiliar Administrativo (OBRAS)', 'C-0009', 'Obra', 'Ativo', NULL),
('Carina Medeiros', 'Almoxarife', 'C-0001', 'Obra', 'Ativo', NULL),
('Andressa Corrêa de Barros', 'Assistente Técnico', 'C-0055', 'Obra', 'Ativo', NULL),
('Dilsilene Rosa da Fonseca', 'Analista Técnico(a) - Obras', 'C-0136', 'Obra', 'Ativo', NULL),
('Joice Peres Ramos', 'Auxiliar de Segurança do Trabalho', 'C-0100', 'Obra', 'Ativo', NULL),
('Claudiane Rafaela Carvalho da Rocha', 'Almoxarife', 'C-0001', 'Obra', 'Ativo', NULL),
('Cassio Peter Lautenschlager', 'Assistente Técnico (pós-obra)', 'C-0055', 'Obra', 'Ativo', NULL),
('Miriam Costa Alves', 'Auxiliar Administrativo (SAC)', 'C-0009', 'Sede', 'Ativo', NULL),
('Taiane de Freitas Gonçalves', 'Auxiliar de Controladoria', 'C-0131', 'Sede', 'Ativo', NULL),
('Milene Valli Quadros', 'Almoxarife', 'C-0001', 'Obra', 'Ativo', NULL),
('Bruna Valeria de Moraes Amaral', 'Coordenador (a) Contábil', NULL, 'Sede', 'Ativo', NULL),
('Lucas Montano Boetege', 'Assistente Técnico', 'C-0055', 'Obra', 'Ativo', NULL),
('Paulo Roberto dos Santos Salum', 'Assistente Técnico', 'C-0055', 'Obra', 'Ativo', NULL),
('Tamara Bohrer Rickes', 'Auxiliar Técnico', 'C-0013', 'Obra', 'Ativo', NULL),
('Pierre Silveira da Cruz', 'Encarregado de Civil', 'C-0084', 'Obra', 'Ativo', NULL),
('Lieser Almeida Wickbolt', 'Auxiliar Administrativo (OBRAS)', 'C-0009', 'Obra', 'Ativo', NULL),
('Joyce Caroline da Silva Marques', 'Assistente Comercial', 'C-0005', 'Sede', 'Ativo', NULL),
('Jeruza da Silva Machado', 'Auxiliar Administrativo (OBRAS)', 'C-0009', 'Obra', 'Ativo', NULL),
('Julia Cardoso Würdig', 'Advogado(a)', 'C-0109', 'Sede', 'Ativo', NULL),
('Daniela Antiqueira dos Santos', 'Analista Comercial', 'C-0147', 'Sede', 'Ativo', NULL),
('Jacqueline Corrêa moraes', 'Técnico(a) em Segurança do Trabalho', 'C-0052', 'Obra', 'Ativo', NULL),
('Mauricio Nunes de Oliveira', 'Assistente Técnico (pós-obra)', 'C-0055', 'Sede', 'Ativo', NULL),
('Ederson Rogerio Martins dos Passos', 'Almoxarife', 'C-0001', 'Obra', 'Ativo', NULL),
('Fabricio Da Silva Wasieleski Pereira', 'Auxiliar Técnico de Qualidade', 'C-0132', 'Obra', 'Ativo', NULL),
('Rafaela Cardoso Pereira', 'Auxiliar Técnico', 'C-0013', 'Obra', 'Ativo', NULL),
('Jonathas Rafael Ucker Viabilizador de', 'Vendas', 'C-0164', 'Sede', 'Ativo', NULL),
('Fabiana Madruga Gonçalves', 'Auxiliar Administrativo - Financeiro', 'C-0009', 'Sede', 'Ativo', NULL),
('Nathália Dorow dos Santos', 'Auxiliar técnico(a) - Pós-obra', 'C-0013', 'Sede', 'Ativo', NULL),
('Krisley Marques Gonçalves', 'Assistente Técnico', 'C-0055', 'Obra', 'Ativo', NULL),
('Laís da Cruz de Lima', 'Jovem Aprendiz', 'C-0076', 'Sede', 'Ativo', NULL),
('Manoela de Borba Prohl', 'Jovem Aprendiz', 'C-0076', 'Sede', 'Ativo', NULL),
('Vitoria Rosário Rosa Quevedo', 'Auxiliar de Contabilidade', 'C-0072', 'Sede', 'Ativo', NULL),
('Alessandra costa cardoso', 'Assistente financeiro - Cobrança', 'C-0007', 'Sede', 'Ativo', NULL),
('ketlen guimarães cavalheiro', 'Período de Experiência', NULL, 'Sede', 'Ativo', NULL),
('Kevin Leal Dias', 'Auxiliar Administrativo (OBRAS)', 'C-0009', 'Obra', 'Ativo', NULL),
('Leonardo Mulling Sainz', 'Auxiliar Técnico de Qualidade', 'C-0132', 'Obra', 'Ativo', NULL),
('Bruno de Souza Gonçalves', 'Psicólogo(a) Organizacional', 'C-0118', 'Sede', 'Ativo', NULL),
('Francine Rodrigues Duarte', 'Jovem Aprendiz', 'C-0076', 'Sede', 'Ativo', NULL),
('Kaiane Medina Teixeira', 'Período de Experiência', NULL, 'Sede', 'Ativo', NULL),
('Otávio Rockembach Machado', 'Período de Experiência', NULL, 'Obra', 'Ativo', NULL),
('Suelen Dias Cavalheiro', 'Auxiliar de Serviços Gerais', 'C-0057', 'Sede', 'Ativo', NULL),
('Isaias de jesus Fernandes', 'Período de Experiência', NULL, 'Obra', 'Ativo', NULL),
('João Paulo Ferreira Porto', 'Período de Experiência', NULL, 'Obra', 'Ativo', NULL),
('Ludson Kennedy valadão Ayres', 'Período de Experiência', NULL, 'Obra', 'Ativo', NULL),
('Nicolas Coelho Boetege', 'Período de Experiência', NULL, 'Obra', 'Ativo', NULL),
('Alessandro Machado Barros', 'Período de Experiência', NULL, 'Sede', 'Ativo', NULL),
('Larissa Moreira Romero', 'Período de Experiência', NULL, 'Sede', 'Ativo', NULL),
('Pamela Sell dos Santos', 'Período de Experiência', NULL, 'Sede', 'Ativo', NULL),
('Samuel Borba Soares', 'Período de Experiência', NULL, 'Obra', 'Ativo', NULL),
('Thales Ferreira Franco', 'Período de Experiência', NULL, 'Sede', 'Ativo', NULL),
('Maria Conceição Da Silva Ferreira', 'Período de Experiência', NULL, 'Sede', 'Ativo', NULL),
('Érica Azevedo Paz', 'ESTAGIÁRIO (A) ENGENHARIA CIVIL CANTEIRO', NULL, 'Obra', 'Ativo', NULL);