-- Inserir as 44 perguntas do Big Five Inventory (Versão em Português - Roiz Junior et al. 2023)
-- Baseado no artigo DOI: 10.47626/2237-6089-2021-0458
-- Domínios: 'O' (Abertura), 'C' (Conscienciosidade), 'E' (Extroversão), 'A' (Amabilidade), 'N' (Neuroticismo)

INSERT INTO public.big_five_questions (item_number, item_text, domain, is_reverse_scored) VALUES
(1, 'Gosta de conversar, é comunicativa.', 'E', false),
(2, 'Tende a encontrar defeitos nos outros.', 'A', true),
(3, 'Faz um trabalho cuidadoso e completo.', 'C', false),
(4, 'É deprimida, melancólica.', 'N', false),
(5, 'É original, tem ideias novas.', 'O', false),
(6, 'É reservada.', 'E', true),
(7, 'É generosa e não é egoísta com outras pessoas.', 'A', false),
(8, 'Pode ser desleixada para fazer as coisas.', 'C', true),
(9, 'É tranquila, lida bem com estresse.', 'N', true),
(10, 'Se interessa por áreas diferentes de conhecimento.', 'O', false),
(11, 'É cheia de energia.', 'E', false),
(12, 'Começa brigas com os outros.', 'A', true),
(13, 'É uma trabalhadora confiável.', 'C', false),
(14, 'Pode ser tensa.', 'N', false),
(15, 'É inovadora, pensa profundamente nas coisas.', 'O', false),
(16, 'Gera muito entusiasmo.', 'E', false),
(17, 'Desculpa, perdoa os outros.', 'A', false),
(18, 'Tende a ser desorganizada.', 'C', true),
(19, 'Se preocupa muito, em excesso.', 'N', false),
(20, 'Tem uma imaginação ativa.', 'O', false),
(21, 'Tende a ser quieta.', 'E', true),
(22, 'Geralmente confia nos outros.', 'A', false),
(23, 'Tende a ser preguiçosa.', 'C', true),
(24, 'É emocionalmente estável, não se perturba facilmente.', 'N', true),
(25, 'É inventiva.', 'O', false),
(26, 'É assertiva, não tem medo de expressar o que sente.', 'E', false),
(27, 'Pode ser fria e distante.', 'A', true),
(28, 'Persevera até concluir as tarefas.', 'C', false),
(29, 'Pode ser temperamental, de humor inconstante.', 'N', false),
(30, 'Valoriza experiências artísticas e estéticas.', 'O', false),
(31, 'É às vezes tímida, inibida.', 'E', true),
(32, 'É boa e atenciosa com quase todo mundo.', 'A', false),
(33, 'Faz as coisas de forma eficiente.', 'C', false),
(34, 'Se mantem calma em situações tensas.', 'N', true),
(35, 'Prefere trabalhos que sejam rotineiros.', 'O', true),
(36, 'É extrovertida, sociável.', 'E', false),
(37, 'É às vezes rude com os outros.', 'A', true),
(38, 'Faz planos e os segue até o fim.', 'C', false),
(39, 'Fica nervosa facilmente.', 'N', false),
(40, 'Gosta de refletir, brincar com as ideias.', 'O', false),
(41, 'Tem poucos interesses artísticos.', 'O', true),
(42, 'Gosta de cooperar com outros.', 'A', false),
(43, 'Se distrai facilmente.', 'C', true),
(44, 'É sofisticada em arte, música ou literatura.', 'O', false);
