INSERT INTO public.psychological_test_norms (test_name, state, division_type, division_name, percentile, score, classification) VALUES
('TEALT', 'PR', 'Geral', 'Geral', 1, 41, 'Inferior'),
('TEALT', 'PR', 'Geral', 'Geral', 5, 53, 'Inferior'),
('TEALT', 'PR', 'Geral', 'Geral', 10, 57, 'Médio Inferior'),
('TEALT', 'PR', 'Geral', 'Geral', 15, 64, 'Médio Inferior'),
('TEALT', 'PR', 'Geral', 'Geral', 20, 71, 'Médio Inferior'),
('TEALT', 'PR', 'Geral', 'Geral', 25, 74, 'Médio Inferior'),
('TEALT', 'PR', 'Geral', 'Geral', 30, 78, 'Médio'),
('TEALT', 'PR', 'Geral', 'Geral', 35, 81, 'Médio'),
('TEALT', 'PR', 'Geral', 'Geral', 40, 85, 'Médio'),
('TEALT', 'PR', 'Geral', 'Geral', 45, 89, 'Médio'),
('TEALT', 'PR', 'Geral', 'Geral', 50, 94, 'Médio'),
('TEALT', 'PR', 'Geral', 'Geral', 55, 99, 'Médio'),
('TEALT', 'PR', 'Geral', 'Geral', 60, 102, 'Médio'),
('TEALT', 'PR', 'Geral', 'Geral', 65, 106, 'Médio'),
('TEALT', 'PR', 'Geral', 'Geral', 70, 110, 'Médio'),
('TEALT', 'PR', 'Geral', 'Geral', 75, 116, 'Médio Superior'),
('TEALT', 'PR', 'Geral', 'Geral', 80, 120, 'Médio Superior'),
('TEALT', 'PR', 'Geral', 'Geral', 85, 124, 'Médio Superior'),
('TEALT', 'PR', 'Geral', 'Geral', 90, 124, 'Médio Superior'),
('TEALT', 'PR', 'Geral', 'Geral', 95, 126, 'Superior'),
('TEALT', 'PR', 'Geral', 'Geral', 99, 128, 'Muito Superior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 1, 73, 'Inferior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 1, 46, 'Inferior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 1, 39, 'Inferior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 1, 25, 'Inferior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 1, -2, 'Inferior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 5, 77, 'Inferior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 5, 49, 'Inferior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 5, 47, 'Inferior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 5, 42, 'Inferior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 5, -2, 'Inferior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 10, 80, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 10, 56, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 10, 50, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 10, 49, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 10, 20, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 15, 84, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 15, 59, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 15, 53, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 15, 52, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 15, 25, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 20, 88, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 20, 66, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 20, 57, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 20, 57, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 20, 42, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 25, 92, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 25, 72, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 25, 59, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 25, 61, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 25, 49, 'Médio Inferior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 30, 97, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 30, 78, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 30, 62, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 30, 64, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 30, 52, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 35, 100, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 35, 80, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 35, 66, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 35, 69, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 35, 57, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 40, 102, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 40, 83, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 40, 68, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 40, 73, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 40, 60, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 45, 106, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 45, 86, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 45, 74, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 45, 75, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 45, 66, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 50, 108, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 50, 93, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 50, 78, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 50, 80, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 50, 69, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 55, 111, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 55, 94, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 55, 85, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 55, 83, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 55, 72, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 60, 117, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 60, 99, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 60, 88, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 60, 88, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 60, 74, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 65, 119, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 65, 101, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 65, 95, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 65, 92, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 65, 77, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 70, 122, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 70, 104, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 70, 101, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 70, 93, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 70, 79, 'Médio'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 75, 125, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 75, 107, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 75, 108, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 75, 102, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 75, 82, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 80, 126, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 80, 112, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 80, 112, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 80, 109, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 80, 86, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 85, 127, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 85, 117, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 85, 117, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 85, 116, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 85, 91, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 90, 128, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 90, 120, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 90, 122, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 90, 118, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 90, 94, 'Médio Superior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 95, 128, 'Superior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 95, 125, 'Superior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 95, 124, 'Superior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 95, 126, 'Superior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 95, 102, 'Superior'),
('TEALT', 'PR', 'Faixa Etária', 'Até 22 anos', 99, 128, 'Muito Superior'),
('TEALT', 'PR', 'Faixa Etária', '23 a 30', 99, 127, 'Muito Superior'),
('TEALT', 'PR', 'Faixa Etária', '31 a 37', 99, 127, 'Muito Superior'),
('TEALT', 'PR', 'Faixa Etária', '38 a 44', 99, 128, 'Muito Superior'),
('TEALT', 'PR', 'Faixa Etária', '45 ou mais', 99, 120, 'Muito Superior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 1, -33, 'Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 1, 4, 'Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 1, 18, 'Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 5, 22, 'Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 5, 53, 'Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 5, 57, 'Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 10, 35, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 10, 61, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 10, 70, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 15, 46, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 15, 69, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 15, 80, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 20, 52, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 20, 74, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 20, 83, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 25, 55, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 25, 77, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 25, 86, 'Médio Inferior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 30, 57, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 30, 81, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 30, 89, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 35, 61, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 35, 85, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 35, 98, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 40, 63, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 40, 88, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 40, 101, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 45, 68, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 45, 93, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 45, 104, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 50, 72, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 50, 97, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 50, 108, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 55, 75, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 55, 101, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 55, 111, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 60, 77, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 60, 105, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 60, 115, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 65, 80, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 65, 107, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 65, 118, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 70, 84, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 70, 110, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 70, 120, 'Médio'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 75, 87, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 75, 114, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 75, 122, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 80, 93, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 80, 118, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 80, 123, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 85, 101, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 85, 122, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 85, 124, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 90, 106, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 90, 125, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 90, 125, 'Médio Superior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 95, 118, 'Superior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 95, 126, 'Superior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 95, 127, 'Superior'),
('TEALT', 'PR', 'Escolaridade', 'Fundamental', 99, 125, 'Muito Superior'),
('TEALT', 'PR', 'Escolaridade', 'Médio', 99, 127, 'Muito Superior'),
('TEALT', 'PR', 'Escolaridade', 'Superior', 99, 128, 'Muito Superior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 1, 13, 'Inferior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 1, 8, 'Inferior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 1, -118, 'Inferior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 1, -119, 'Inferior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 1, -123, 'Inferior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 5, 43, 'Inferior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 5, 50, 'Inferior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 5, -24, 'Inferior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 5, 22, 'Inferior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 5, -64, 'Inferior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 10, 51, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 10, 64, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 10, 36, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 10, 41, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 10, 18, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 15, 64, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 15, 71, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 15, 48, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 15, 49, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 15, 37, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 20, 76, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 20, 80, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 20, 53, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 20, 58, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 20, 42, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 25, 80, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 25, 84, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 25, 58, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 25, 61, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 25, 52, 'Médio Inferior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 30, 84, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 30, 88, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 30, 62, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 30, 64, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 30, 56, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 35, 88, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 35, 93, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 35, 66, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 35, 68, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 35, 60, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 40, 93, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 40, 97, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 40, 70, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 40, 72, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 40, 61, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 45, 97, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 45, 99, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 45, 74, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 45, 78, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 45, 65, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 50, 99, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 50, 104, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 50, 77, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 50, 80, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 50, 70, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 55, 104, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 55, 106, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 55, 82, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 55, 84, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 55, 73, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 60, 106, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 60, 110, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 60, 84, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 60, 87, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 60, 75, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 65, 110, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 65, 115, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 65, 85, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 65, 88, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 65, 78, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 70, 115, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 70, 124, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 70, 91, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 70, 91, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 70, 85, 'Médio'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 75, 124, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 75, 126, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 75, 93, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 75, 97, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 75, 89, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 80, 126, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 80, 126, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 80, 102, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 80, 101, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 80, 92, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 85, 126, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 85, 127, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 85, 118, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 85, 120, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 85, 100, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 90, 127, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 90, 128, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 90, 122, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 90, 122, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 90, 102, 'Médio Superior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 95, 128, 'Superior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 95, 128, 'Superior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 95, 126, 'Superior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 95, 126, 'Superior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 95, 106, 'Superior'),
('TEALT', 'SC', 'Faixa Etária', 'Até 22 anos', 99, 128, 'Muito Superior'),
('TEALT', 'SC', 'Faixa Etária', '23 a 30', 99, 128, 'Muito Superior'),
('TEALT', 'SC', 'Faixa Etária', '31 a 37', 99, 127, 'Muito Superior'),
('TEALT', 'SC', 'Faixa Etária', '38 a 44', 99, 128, 'Muito Superior'),
('TEALT', 'SC', 'Faixa Etária', '45 ou mais', 99, 128, 'Muito Superior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 1, -120, 'Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 1, -9, 'Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 1, 54, 'Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 5, 40, 'Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 5, 43, 'Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 5, 62, 'Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 10, 49, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 10, 52, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 10, 69, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 15, 53, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 15, 64, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 15, 79, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 20, 56, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 20, 70, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 20, 80, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 25, 59, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 25, 75, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 25, 84, 'Médio Inferior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 30, 62, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 30, 79, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 30, 85, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 35, 64, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 35, 82, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 35, 88, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 40, 67, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 40, 86, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 40, 93, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 45, 70, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 45, 92, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 45, 96, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 50, 73, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 50, 97, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 50, 102, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 55, 75, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 55, 100, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 55, 104, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 60, 79, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 60, 104, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 60, 107, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 65, 83, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 65, 106, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 65, 112, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 70, 88, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 70, 114, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 70, 116, 'Médio'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 75, 92, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 75, 118, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 75, 120, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 80, 102, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 80, 124, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 80, 124, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 85, 116, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 85, 125, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 85, 125, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 90, 126, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 90, 126, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 90, 126, 'Médio Superior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 95, 128, 'Superior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 95, 127, 'Superior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 95, 127, 'Superior'),
('TEALT', 'SC', 'Escolaridade', 'Fundamental', 99, 128, 'Muito Superior'),
('TEALT', 'SC', 'Escolaridade', 'Médio', 99, 128, 'Muito Superior'),
('TEALT', 'SC', 'Escolaridade', 'Superior', 99, 128, 'Muito Superior'),
('TEALT', 'SP', 'Geral', 'Geral', 1, -27, 'Inferior'),
('TEALT', 'SP', 'Geral', 'Geral', 5, 40, 'Inferior'),
('TEALT', 'SP', 'Geral', 'Geral', 10, 51, 'Médio Inferior'),
('TEALT', 'SP', 'Geral', 'Geral', 15, 58, 'Médio Inferior'),
('TEALT', 'SP', 'Geral', 'Geral', 20, 64, 'Médio Inferior'),
('TEALT', 'SP', 'Geral', 'Geral', 25, 70, 'Médio Inferior'),
('TEALT', 'SP', 'Geral', 'Geral', 30, 74, 'Médio'),
('TEALT', 'SP', 'Geral', 'Geral', 35, 78, 'Médio'),
('TEALT', 'SP', 'Geral', 'Geral', 40, 80, 'Médio'),
('TEALT', 'SP', 'Geral', 'Geral', 45, 84, 'Médio'),
('TEALT', 'SP', 'Geral', 'Geral', 50, 88, 'Médio'),
('TEALT', 'SP', 'Geral', 'Geral', 55, 91, 'Médio'),
('TEALT', 'SP', 'Geral', 'Geral', 60, 97, 'Médio'),
('TEALT', 'SP', 'Geral', 'Geral', 65, 100, 'Médio'),
('TEALT', 'SP', 'Geral', 'Geral', 70, 103, 'Médio'),
('TEALT', 'SP', 'Geral', 'Geral', 75, 107, 'Médio Superior'),
('TEALT', 'SP', 'Geral', 'Geral', 80, 112, 'Médio Superior'),
('TEALT', 'SP', 'Geral', 'Geral', 85, 119, 'Médio Superior'),
('TEALT', 'SP', 'Geral', 'Geral', 90, 123, 'Médio Superior'),
('TEALT', 'SP', 'Geral', 'Geral', 95, 126, 'Superior'),
('TEALT', 'SP', 'Geral', 'Geral', 99, 128, 'Muito Superior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 1, 33, 'Inferior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 1, -86, 'Inferior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 1, -92, 'Inferior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 1, 19, 'Inferior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 1, -115, 'Inferior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 5, 54, 'Inferior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 5, 34, 'Inferior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 5, 36, 'Inferior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 5, 22, 'Inferior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 5, 22, 'Inferior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 10, 60, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 10, 44, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 10, 46, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 10, 27, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 10, 37, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 15, 66, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 15, 50, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 15, 51, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 15, 38, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 15, 43, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 20, 70, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 20, 55, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 20, 54, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 20, 46, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 20, 48, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 25, 73, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 25, 60, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 25, 59, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 25, 50, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 25, 56, 'Médio Inferior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 30, 78, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 30, 65, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 30, 65, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 30, 54, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 30, 58, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 35, 80, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 35, 67, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 35, 68, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 35, 61, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 35, 61, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 40, 83, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 40, 70, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 40, 73, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 40, 64, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 40, 68, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 45, 87, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 45, 73, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 45, 76, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 45, 65, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 45, 73, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 50, 93, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 50, 77, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 50, 78, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 50, 69, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 50, 75, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 55, 97, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 55, 80, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 55, 79, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 55, 71, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 55, 79, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 60, 100, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 60, 83, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 60, 81, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 60, 76, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 60, 84, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 65, 101, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 65, 87, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 65, 83, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 65, 82, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 65, 92, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 70, 104, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 70, 93, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 70, 86, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 70, 88, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 70, 98, 'Médio'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 75, 108, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 75, 97, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 75, 91, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 75, 96, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 75, 104, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 80, 113, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 80, 101, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 80, 101, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 80, 108, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 80, 111, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 85, 118, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 85, 106, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 85, 106, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 85, 113, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 85, 118, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 90, 122, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 90, 113, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 90, 118, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 90, 116, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 90, 123, 'Médio Superior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 95, 124, 'Superior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 95, 122, 'Superior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 95, 125, 'Superior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 95, 121, 'Superior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 95, 126, 'Superior'),
('TEALT', 'SP', 'Faixa Etária', 'Até 22 anos', 99, 127, 'Muito Superior'),
('TEALT', 'SP', 'Faixa Etária', '23 a 30', 99, 128, 'Muito Superior'),
('TEALT', 'SP', 'Faixa Etária', '31 a 37', 99, 128, 'Muito Superior'),
('TEALT', 'SP', 'Faixa Etária', '38 a 44', 99, 128, 'Muito Superior'),
('TEALT', 'SP', 'Faixa Etária', '45 ou mais', 99, 128, 'Muito Superior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 1, -90, 'Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 1, 3, 'Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 1, 33, 'Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 5, 20, 'Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 5, 34, 'Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 5, 54, 'Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 10, 34, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 10, 43, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 10, 61, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 15, 43, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 15, 51, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 15, 66, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 20, 47, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 20, 55, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 20, 68, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 25, 51, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 25, 58, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 25, 70, 'Médio Inferior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 30, 55, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 30, 60, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 30, 73, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 35, 58, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 35, 63, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 35, 76, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 40, 60, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 40, 64, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 40, 80, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 45, 63, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 45, 68, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 45, 83, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 50, 64, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 50, 71, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 50, 87, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 55, 68, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 55, 75, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 55, 97, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 60, 70, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 60, 80, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 60, 101, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 65, 75, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 65, 84, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 65, 105, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 70, 80, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 70, 90, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 70, 115, 'Médio'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 75, 84, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 75, 103, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 75, 120, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 80, 88, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 80, 107, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 80, 122, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 85, 102, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 85, 112, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 85, 124, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 90, 112, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 90, 122, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 90, 126, 'Médio Superior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 95, 122, 'Superior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 95, 126, 'Superior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 95, 127, 'Superior'),
('TEALT', 'SP', 'Escolaridade', 'Fundamental', 99, 126, 'Muito Superior'),
('TEALT', 'SP', 'Escolaridade', 'Médio', 99, 128, 'Muito Superior'),
('TEALT', 'SP', 'Escolaridade', 'Superior', 99, 128, 'Muito Superior'),
('TEALT', 'SE', 'Geral', 'Geral', 1, -84, 'Inferior'),
('TEALT', 'SE', 'Geral', 'Geral', 5, 63, 'Inferior'),
('TEALT', 'SE', 'Geral', 'Geral', 10, 77, 'Médio Inferior'),
('TEALT', 'SE', 'Geral', 'Geral', 15, 93, 'Médio Inferior'),
('TEALT', 'SE', 'Geral', 'Geral', 20, 98, 'Médio Inferior'),
('TEALT', 'SE', 'Geral', 'Geral', 25, 104, 'Médio Inferior'),
('TEALT', 'SE', 'Geral', 'Geral', 30, 107, 'Médio'),
('TEALT', 'SE', 'Geral', 'Geral', 35, 111, 'Médio'),
('TEALT', 'SE', 'Geral', 'Geral', 40, 115, 'Médio'),
('TEALT', 'SE', 'Geral', 'Geral', 45, 118, 'Médio'),
('TEALT', 'SE', 'Geral', 'Geral', 50, 119, 'Médio'),
('TEALT', 'SE', 'Geral', 'Geral', 55, 120, 'Médio'),
('TEALT', 'SE', 'Geral', 'Geral', 60, 121, 'Médio'),
('TEALT', 'SE', 'Geral', 'Geral', 65, 122, 'Médio'),
('TEALT', 'SE', 'Geral', 'Geral', 70, 123, 'Médio'),
('TEALT', 'SE', 'Geral', 'Geral', 75, 124, 'Médio Superior'),
('TEALT', 'SE', 'Geral', 'Geral', 80, 125, 'Médio Superior'),
('TEALT', 'SE', 'Geral', 'Geral', 85, 126, 'Médio Superior'),
('TEALT', 'SE', 'Geral', 'Geral', 90, 126, 'Médio Superior'),
('TEALT', 'SE', 'Geral', 'Geral', 95, 127, 'Superior'),
('TEALT', 'SE', 'Geral', 'Geral', 99, 128, 'Muito Superior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 1, -12, 'Inferior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 1, -18, 'Inferior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 1, -60, 'Inferior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 1, -25, 'Inferior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 1, -20, 'Inferior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 5, 69, 'Inferior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 5, 64, 'Inferior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 5, 30, 'Inferior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 5, 62, 'Inferior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 5, 23, 'Inferior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 10, 88, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 10, 77, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 10, 62, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 10, 68, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 10, 24, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 15, 98, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 15, 83, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 15, 68, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 15, 76, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 15, 29, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 20, 104, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 20, 88, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 20, 71, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 20, 80, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 20, 40, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 25, 107, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 25, 94, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 25, 83, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 25, 87, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 25, 52, 'Médio Inferior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 30, 111, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 30, 97, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 30, 88, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 30, 89, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 30, 58, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 35, 116, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 35, 101, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 35, 93, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 35, 89, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 35, 67, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 40, 118, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 40, 104, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 40, 98, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 40, 94, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 40, 86, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 45, 120, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 45, 108, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 45, 110, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 45, 104, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 45, 96, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 50, 122, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 50, 112, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 50, 115, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 50, 106, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 50, 104, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 55, 123, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 55, 116, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 55, 117, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 55, 109, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 55, 110, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 60, 124, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 60, 119, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 60, 119, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 60, 114, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 60, 111, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 65, 125, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 65, 120, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 65, 121, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 65, 116, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 65, 112, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 70, 126, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 70, 121, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 70, 122, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 70, 117, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 70, 114, 'Médio'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 75, 126, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 75, 123, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 75, 124, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 75, 119, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 75, 115, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 80, 127, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 80, 124, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 80, 126, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 80, 121, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 80, 122, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 85, 127, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 85, 125, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 85, 126, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 85, 123, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 85, 124, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 90, 128, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 90, 126, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 90, 127, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 90, 125, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 90, 125, 'Médio Superior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 95, 128, 'Superior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 95, 127, 'Superior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 95, 127, 'Superior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 95, 126, 'Superior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 95, 126, 'Superior'),
('TEALT', 'SE', 'Faixa Etária', 'Até 22 anos', 99, 128, 'Muito Superior'),
('TEALT', 'SE', 'Faixa Etária', '23 a 30', 99, 128, 'Muito Superior'),
('TEALT', 'SE', 'Faixa Etária', '31 a 37', 99, 128, 'Muito Superior'),
('TEALT', 'SE', 'Faixa Etária', '38 a 44', 99, 128, 'Muito Superior'),
('TEALT', 'SE', 'Faixa Etária', '45 ou mais', 99, 127, 'Muito Superior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 1, 35, 'Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 1, 48, 'Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 1, 11, 'Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 5, 44, 'Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 5, 59, 'Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 5, 62, 'Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 10, 50, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 10, 66, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 10, 77, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 15, 67, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 15, 76, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 15, 83, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 20, 64, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 20, 80, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 20, 88, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 25, 67, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 25, 84, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 25, 92, 'Médio Inferior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 30, 69, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 30, 88, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 30, 95, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 35, 71, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 35, 93, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 35, 99, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 40, 74, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 40, 97, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 40, 101, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 45, 81, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 45, 100, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 45, 104, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 50, 85, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 50, 102, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 50, 106, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 55, 89, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 55, 106, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 55, 109, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 60, 94, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 60, 110, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 60, 111, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 65, 98, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 65, 113, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 65, 115, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 70, 102, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 70, 117, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 70, 117, 'Médio'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 75, 108, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 75, 120, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 75, 122, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 80, 118, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 80, 124, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 80, 124, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 85, 124, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 85, 125, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 85, 125, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 90, 126, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 90, 127, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 90, 127, 'Médio Superior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 95, 128, 'Superior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 95, 128, 'Superior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 95, 128, 'Superior'),
('TEALT', 'MS', 'Escolaridade', 'Fundamental', 99, 128, 'Muito Superior'),
('TEALT', 'MS', 'Escolaridade', 'Médio', 99, 128, 'Muito Superior'),
('TEALT', 'MS', 'Escolaridade', 'Superior', 99, 128, 'Muito Superior')
ON CONFLICT (test_name, state, division_type, division_name, percentile) DO UPDATE SET score = EXCLUDED.score, classification = EXCLUDED.classification;