export const tabela32 = {
  nome: "Tabela 32",
  descricao:
    "Estatísticas, pontuação, percentis e classificação da atenção concentrada, por nível de escolaridade para a amostra da Bahia",
  colunas: [
    "Percentil",
    "Ensino fundamental completo e incompleto",
    "Ensino médio completo e incompleto",
    "Ensino superior completo e incompleto",
  ],
  dados: [
    {
      percentil: 10,
      "Ensino fundamental completo e incompleto": 48,
      "Ensino médio completo e incompleto": 78,
      "Ensino superior completo e incompleto": 113,
      classificacao: "Inferior",
    },
    {
      percentil: 20,
      "Ensino fundamental completo e incompleto": 62,
      "Ensino médio completo e incompleto": 89,
      "Ensino superior completo e incompleto": 122,
      classificacao: "Médio Inferior",
    },
    {
      percentil: 25,
      "Ensino fundamental completo e incompleto": 67,
      "Ensino médio completo e incompleto": 92,
      "Ensino superior completo e incompleto": 124,
      classificacao: "Médio Inferior",
    },
    {
      percentil: 30,
      "Ensino fundamental completo e incompleto": 70,
      "Ensino médio completo e incompleto": 95,
      "Ensino superior completo e incompleto": 125,
      classificacao: "Médio Inferior",
    },
    {
      percentil: 40,
      "Ensino fundamental completo e incompleto": 75,
      "Ensino médio completo e incompleto": 101,
      "Ensino superior completo e incompleto": 132,
      classificacao: "Médio",
    },
    {
      percentil: 50,
      "Ensino fundamental completo e incompleto": 85,
      "Ensino médio completo e incompleto": 107,
      "Ensino superior completo e incompleto": 135,
      classificacao: "Médio",
    },
    {
      percentil: 60,
      "Ensino fundamental completo e incompleto": 89,
      "Ensino médio completo e incompleto": 115,
      "Ensino superior completo e incompleto": 137,
      classificacao: "Médio",
    },
    {
      percentil: 70,
      "Ensino fundamental completo e incompleto": 96,
      "Ensino médio completo e incompleto": 123,
      "Ensino superior completo e incompleto": 141,
      classificacao: "Médio Superior",
    },
    {
      percentil: 75,
      "Ensino fundamental completo e incompleto": 100,
      "Ensino médio completo e incompleto": 127,
      "Ensino superior completo e incompleto": 144,
      classificacao: "Médio Superior",
    },
    {
      percentil: 80,
      "Ensino fundamental completo e incompleto": 105,
      "Ensino médio completo e incompleto": 134,
      "Ensino superior completo e incompleto": 147,
      classificacao: "Médio Superior",
    },
    {
      percentil: 90,
      "Ensino fundamental completo e incompleto": 116,
      "Ensino médio completo e incompleto": 148,
      "Ensino superior completo e incompleto": 151,
      classificacao: "Superior",
    },
  ],
};
