export const tabela26 = {
  nome: "Tabela 26",
  descricao:
    "Estatísticas, pontuação, percentis e classificação da atenção concentrada, por nível de escolaridade",
  colunas: [
    "Percentil",
    "Ensino fundamental completo e incompleto",
    "Ensino médio completo e incompleto",
    "Ensino superior completo e incompleto",
  ],
  dados: [
    {
      percentil: 10,
      "Ensino fundamental completo e incompleto": 48,
      "Ensino médio completo e incompleto": 78,
      "Ensino superior completo e incompleto": 90,
      classificacao: "Inferior",
    },
    {
      percentil: 20,
      "Ensino fundamental completo e incompleto": 62,
      "Ensino médio completo e incompleto": 89,
      "Ensino superior completo e incompleto": 100,
      classificacao: "Médio Inferior",
    },
    {
      percentil: 25,
      "Ensino fundamental completo e incompleto": 67,
      "Ensino médio completo e incompleto": 92,
      "Ensino superior completo e incompleto": 106,
      classificacao: "Médio Inferior",
    },
    {
      percentil: 30,
      "Ensino fundamental completo e incompleto": 70,
      "Ensino médio completo e incompleto": 95,
      "Ensino superior completo e incompleto": 111,
      classificacao: "Médio Inferior",
    },
    {
      percentil: 40,
      "Ensino fundamental completo e incompleto": 75,
      "Ensino médio completo e incompleto": 101,
      "Ensino superior completo e incompleto": 118,
      classificacao: "Médio",
    },
    {
      percentil: 50,
      "Ensino fundamental completo e incompleto": 85,
      "Ensino médio completo e incompleto": 107,
      "Ensino superior completo e incompleto": 123,
      classificacao: "Médio",
    },
    {
      percentil: 60,
      "Ensino fundamental completo e incompleto": 89,
      "Ensino médio completo e incompleto": 115,
      "Ensino superior completo e incompleto": 130,
      classificacao: "Médio",
    },
    {
      percentil: 70,
      "Ensino fundamental completo e incompleto": 96,
      "Ensino médio completo e incompleto": 123,
      "Ensino superior completo e incompleto": 137,
      classificacao: "Médio Superior",
    },
    {
      percentil: 75,
      "Ensino fundamental completo e incompleto": 100,
      "Ensino médio completo e incompleto": 127,
      "Ensino superior completo e incompleto": 139,
      classificacao: "Médio Superior",
    },
    {
      percentil: 80,
      "Ensino fundamental completo e incompleto": 105,
      "Ensino médio completo e incompleto": 133,
      "Ensino superior completo e incompleto": 143,
      classificacao: "Médio Superior",
    },
    {
      percentil: 90,
      "Ensino fundamental completo e incompleto": 116,
      "Ensino médio completo e incompleto": 147,
      "Ensino superior completo e incompleto": 153,
      classificacao: "Superior",
    },
  ],
};
