import uuid, re

missing = [
    ("19845", "LEONARDO BEDERODE DOS SANTOSCOORDENADOR DE SMS", "491"),
    ("19850", "NATHALI DOS SANTOS PORTO AUX ADMINISTRATIVO", "491"),
    ("19859", "VITORIA TEIXEIRA PINTO COORDENADOR DE", "491"),
    ("19901", "NATHALIA DOROW DOS SANTOS ASSISTENTE TECNICO", "519"),
    ("19420", "CARINA MEDEIROS ALMOXARIFE", "10867"),
    ("19805", "GUILHERME BORGES LAGES AUX ADMINISTRATIVO", "10867"),
    ("19888", "VALDILENE NEGRAO DE FARIAS TEC. SEG. DO TRABALHO", "10867"),
    ("19421", "EGICLEIDE DIAS SILVA TEC. SEG. DO TRABALHO", "10963"),
    ("19913", "CHARLES AVILA WITTER SERVENTE", "10867"),
    ("19694", "JOSE RENATO LUCAS DA SILVA SERVENTE", "10867"),
    ("19485", "LAIS DA CRUZ DE LIMA JOVEM APRENDIZ", "10867"),
    ("19769", "LUIS FELIPE CUNHA LEROY SERVENTE", "10867"),
    ("19780", "ALEX SANDER GOMES MEDEIROS SERVENTE", "10980"),
    ("19773", "ALVARO DA SILVA CONCEIÇÃO MOTORISTA/OPERADOR", "967"),
    ("19645", "ANDERSON PORTO MACHADO SERVENTE", "10980"),
    ("19696", "ANTONIO CARLOS COSTA PERES MOTORISTA MUNCK", "10893"),
    ("19668", "CARLOS HENRIQUE BARNECHE SCAHUMXIIDLTI AR TECNICO", "10980"), # SCAHUMXIIDLTI AR TECNICO? -> CARLOS HENRIQUE BARNECHE SCHUMACHER? Let's just strip " AR TECNICO"
    ("19734", "DERICK BORBA GARCIA SERVENTE", "10980"),
    ("19778", "EDIPO SOUZA DUARTE PEDREIRO", "10980"),
    ("19910", "ELISANGELA KANIGOSKI HORNKEAUX SERVICOS GERAIS", "10780"),
    ("19880", "FELIZ LOPES PEDREIRO", "10861"),
    ("19787", "GLEDSON ALEX GONCALVES AIRESSERVENTE", "10980"),
    ("19789", "HELMUTE RODRIGUES NACHTIGALPEDREIRO", "10980"),
    ("19674", "JEREMIAS GARCIA FREITAS SERVENTE", "10980"),
    ("19790", "JOICE ALEXANDRA DOS SANTOS AGNOANLCIASLTVAE STÉCNICO", "10980"),
    ("19693", "JORGE LUIZ MELLO VIEIRA FILSHEOR VENTE", "10980"),
    ("19742", "LIONARA DA SILVA FERNANDES SERVENTE", "10980"),
    ("19906", "LUIS CARLOS SILVEIRA SILVA PEDREIRO", "10980"),
    ("19792", "MARIA LEONICE GONCALVES LOPAEUSX SERVICOS GERAIS", "10980"),
    ("19794", "MATEUS GOMES DA SILVA INSTALADOR HIDRAULICO", "10980"),
    ("19681", "MICHEL MOISES SALGADO NEITZSKEERVENTE", "10980"),
    ("19796", "NADIR OLIVEIRA MESQUITA 1/2 OFICIAL", "10980"),
    ("19757", "NELSON OLIVEIRA SERVENTE", "10980"),
    ("19772", "OTAVIO ROCKEMBACH MACHADO AUXILIAR TECNICO", "10980"),
    ("19611", "PAULO CESAR ABREU JARDIM SERVENTE", "10980"),
    ("19725", "PROCESSO MILTON ROSA FREITAPSE DREIRO", "10980"),
    ("19748", "RAFAEL DE RODRIGUES SERVENTE", "10980"),
    ("19582", "RAFAEL SEUS VILELLA AUX DE ALMOXARIFADO", "10980"),
    ("19867", "SERGIO ELIAS BICHET BORGES OPER.RETRO ESCAVADEIRA", "10780"),
    ("19749", "SIDINEI BEHLING ZITZKE PEDREIRO", "10980"),
    ("19727", "WALTER DIEGO BARBOSA MIRANDSAE RVENTE", "10980"),
    ("19813", "JERUZA DA SILVA MACHADO AUX ADMINISTRATIVO", "10893"),
    ("19917", "JOAO MARCIO MACHADO DOS SANPTEODSREIRO", "10893"),
    ("19823", "PIERRE SILVEIRA DA CRUZ ENCARREGADO (A) DE CIVIL", "988"),
    ("19824", "RAFAELA CARDOSO PEREIRA AUXILIAR TECNICO", "988")
]

cargos = [
    "COORDENADOR DE SMS", "AUX ADMINISTRATIVO", "COORDENADOR DE", "ASSISTENTE TECNICO",
    "ALMOXARIFE", "TEC. SEG. DO TRABALHO", "SERVENTE", "JOVEM APRENDIZ", "MOTORISTA/OPERADOR",
    "MOTORISTA MUNCK", "AR TECNICO", "PEDREIRO", "AUX SERVICOS GERAIS", "INSTALADOR HIDRAULICO",
    "1/2 OFICIAL", "AUXILIAR TECNICO", "AUX DE ALMOXARIFADO", "OPER.RETRO ESCAVADEIRA",
    "ENCARREGADO (A) DE CIVIL", "ASSISTENTE DE", "MECANICO", "STÉCNICO", "FILSHEOR VENTE"
]

def clean_name(name):
    # OCR mistakes like "DOS SANTOSCOORDENADOR"
    name = name.replace("SANTOSCOORDENADOR DE SMS", "SANTOS")
    name = name.replace("HORNKEAUX SERVICOS GERAIS", "HORNKE")
    name = name.replace("NACHTIGALPEDREIRO", "NACHTIGAL")
    name = name.replace("AIRESSERVENTE", "AIRES")
    name = name.replace("AGNOANLCIASLTVAE STÉCNICO", "AGNOANLCIASLTVAE") # messy OCR
    name = name.replace("FILSHEOR VENTE", "FILHO")
    name = name.replace("LOPAEUSX SERVICOS GERAIS", "LOPES")
    name = name.replace("NEITZSKEERVENTE", "NEITZSKE")
    name = name.replace("FREITAPSE DREIRO", "FREITAS")
    name = name.replace("MIRANDSAE RVENTE", "MIRANDA")
    name = name.replace("SANPTEODSREIRO", "SANTOS")
    name = name.replace("SCAHUMXIIDLTI AR TECNICO", "SCHUMACHER")
    
    # Sort cargos by length descending so longer titles match first
    for c in sorted(cargos, key=len, reverse=True):
        if name.endswith(" " + c):
            name = name[:-len(c)-1]
        elif name.endswith(c):
            name = name[:-len(c)]
    
    return name.strip()

def title_case(name):
    words = name.split()
    lowers = ['da', 'de', 'do', 'das', 'dos', 'e']
    res = []
    for i, w in enumerate(words):
        w = w.title()
        if w.lower() in lowers and i > 0 and i < len(words) - 1:
            w = w.lower()
        res.append(w)
    return " ".join(res)

for mat, name, cc in missing:
    cleaned = clean_name(name)
    titled = title_case(cleaned)
    print(f"{mat} | {titled}")
